### ISSUE TITLE
[mympirun v4.0.0 beta] --universe isn't balanced over available nodes

### ISSUE THREAD

**Issue by Caylo** [hpcugent/vsc-mympirun#119]
both with the latest version(s) of impi and ompi, the load when using `--universe` is all put on one node instead of dividing the processes over both nodes

**Comment by Caylo** [comment]
see universe v world in openmpi https://www.open-mpi.org/faq/?category=running#mpi-environmental-variables

**Comment by boegel** [comment]
fixed in #128
