### ISSUE TITLE
mympirun is reported to only start 1 process on each physical node

### ISSUE THREAD

**Issue by ehiggs** [hpcugent/vsc-mympirun#34]
Users are reporting that mympirun is starting only 1 process per physical node. So in a job where you have nodes=4:ppn=2 and 2 of these logical nodes land on the same physical node, then it's not starting multiple processes. If this is the case, it's really broken.

**Comment by Caylo** [comment]
@stdweird is this still an issue?

**Comment by stdweird** [comment]
@Caylo dunno, maybe just try it?

**Comment by boegel** [comment]
@Caylo some debug info using current `develop` (after merging of #92) @ https://github.ugent.be/gist/kehoste/b484c8435dc07dbce50a65694e853687

**Comment by boegel** [comment]
@Caylo in that example, Torque gave us 16 cores on one node, 4 cores on the other node, so `mympirun` should be honouring that:

* in 'normal' mode, start 16 processes on 1st node, 4 processes on other node
* with `--hybrid 2`, start 2 processes on each node (`#hybrid` per unique node), but also print a warning (only for hybrid mode) w.r.t. the imbalance of cores-per-node (combining `--hybrid` and partial nodes doesn't make much sense)
* with `--double`, start 32 processes on 1st node, 8 processes on other node

**Comment by boegel** [comment]
fixed in #93
