### ISSUE TITLE
--sched was renamed to --setsched, should be reverted

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-mympirun#81]
@Caylo also take a look at the other cmdline options in the current `develop` version (use the `mympirun` you get by loading the `scripts` module on the HPC-UGent infrastructure as a reference)

**Comment by Caylo** [comment]
the other cmdline options seem fine to me

**Comment by Caylo** [comment]
the reason `--sched` works on master rn is because it aliases to `--schedtype`.  in fact every substring of `schedtype` aliases to it. 

`-bash-4.1$ mympirun --sch local ./mpi_helloworld` is apparently perfectly acceptable. i'm not sure if this is a feature or a bug in generaloption

**Comment by boegel** [comment]
@Caylo hah, ok... That's a feature, but probably not of generaloption, but of the Python `optparser` underneath.

Follow-up in #83
