### ISSUE TITLE
don't hardcode sockets_per_node in openmpi.py

### ISSUE THREAD

**Issue by Caylo** [hpcugent/vsc-mympirun#97]
either figure out what sockets_per_node is or make it an option?
https://github.com/hpcugent/vsc-mympirun/blob/develop/lib/vsc/mympirun/mpi/openmpi.py#L69

**Comment by boegel** [comment]
figuring out dynamically how many sockets are really there may be tricky to implement reliably...

**Comment by stdweird** [comment]
there's code in mympingpong that does things like that based on hwloc output

**Comment by boegel** [comment]
@stdweird this? https://github.com/hpcugent/mympingpong/blob/master/bin/mympingpong.py#L149

**Comment by boegel** [comment]
fixed in #127, #129
