### ISSUE TITLE
fix how --double and --hybrid work together

### ISSUE THREAD

**Issue by Caylo** [hpcugent/vsc-mympirun#98]
right now using `--double` and `--hybrid`will use the hybrid option as a multiplier
what it has to be:
- give `--double` an argument (store_or_None)
- conflict `--double`and `--hybrid`

**Comment by boegel** [comment]
actual fix implemented in #101 

* new option: `--multi` to specify a custom multiplier
* `--double` always means running twice # processes (equivalent to `--multi 2`)
* `--hybrid` is no longer a multiplier when combined with `--double`, always means "run N processes per node rather than #cores"
